version: '0.1'

services:
  web:
    container_name: web
    user: root
    build:
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 #gunicorn saloncrm.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/home/django/
    ports: 
      - 80:8000
    env_file:
      - ./.env.web
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    volumes:
     - ./db:/var/lib/postgresql/data
    env_file:
      - ./.env.db